#!/bin/bash

TORRENT_PATH=/srv/http/bt/

if [ "$1" != "" ] && [ "$2" != "" ]; then

    /usr/bin/btmakemetafile.py http://"$2":6881/announce $1 > /dev/null 2>&1
    
    if [ "$?" -ne 0 ]; then
        echo "Wrong filename, or no permission to write file."
    else
        echo "Generate "$1".torrent Successful!"
        echo
        echo "if you want to upload file, Use \"papa-btdownloadcurses\""
    fi
else
    echo "Help: papa-btmakemetafile <filename> <tracker ip>"
fi
